# Assignment 3

## Task1

#### 1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [10]:
def divide():
    print('Dividing 5/0')
    try:
        k= 5/0
    except Exception as e:
        print(e)
        
divide()

Dividing 5/0
division by zero


#### 2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [11]:
Subject=["Americans","Indians"]
Verb=["play","watch"]
Object=["Baseball","Cricket"]
for i in Subject:
    for j in Verb:
        for k in Object:
            print("%s %s %s"%(i,j,k))
            

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

#### 1.


In [14]:
import numpy as np
def ATVander(iv,increasing):
    N=len(iv)
    if(increasing==True):
        k=[]
        for i in iv:
            l=[]
            for j in range(0,N):
                l.append(i**j)
            k.append(l)
        k= np.array(k)
        return k

    elif(increasing==False):
        k=[]
        for i in iv:
            l=[]
            for j in range(0,N):
                l.append(i**(N-j-1))
            k.append(l) 
        k= np.array(k)
        return k
    
print(ATVander([2,3,4,5,6,7],True))
print('-'*60)
print(ATVander([2,3,4,5,6,7],False))

[[    1     2     4     8    16    32]
 [    1     3     9    27    81   243]
 [    1     4    16    64   256  1024]
 [    1     5    25   125   625  3125]
 [    1     6    36   216  1296  7776]
 [    1     7    49   343  2401 16807]]
------------------------------------------------------------
[[   32    16     8     4     2     1]
 [  243    81    27     9     3     1]
 [ 1024   256    64    16     4     1]
 [ 3125   625   125    25     5     1]
 [ 7776  1296   216    36     6     1]
 [16807  2401   343    49     7     1]]
